// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package edu.stanford.smi.protege.server;

public final class ServerFrameStore_Stub
    extends java.rmi.server.RemoteStub
    implements edu.stanford.smi.protege.server.RemoteServerFrameStore, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addDirectSuperclass_0;
    private static java.lang.reflect.Method $method_addDirectSuperslot_1;
    private static java.lang.reflect.Method $method_addDirectTemplateSlot_2;
    private static java.lang.reflect.Method $method_addDirectType_3;
    private static java.lang.reflect.Method $method_beginTransaction_4;
    private static java.lang.reflect.Method $method_close_5;
    private static java.lang.reflect.Method $method_commitTransaction_6;
    private static java.lang.reflect.Method $method_createCls_7;
    private static java.lang.reflect.Method $method_createFacet_8;
    private static java.lang.reflect.Method $method_createSimpleInstance_9;
    private static java.lang.reflect.Method $method_createSlot_10;
    private static java.lang.reflect.Method $method_deleteCls_11;
    private static java.lang.reflect.Method $method_deleteFacet_12;
    private static java.lang.reflect.Method $method_deleteSimpleInstance_13;
    private static java.lang.reflect.Method $method_deleteSlot_14;
    private static java.lang.reflect.Method $method_executeQuery_15;
    private static java.lang.reflect.Method $method_getClsCount_16;
    private static java.lang.reflect.Method $method_getClses_17;
    private static java.lang.reflect.Method $method_getClsesWithAnyDirectTemplateSlotValue_18;
    private static java.lang.reflect.Method $method_getClsesWithDirectTemplateFacetValue_19;
    private static java.lang.reflect.Method $method_getClsesWithDirectTemplateSlotValue_20;
    private static java.lang.reflect.Method $method_getClsesWithMatchingDirectTemplateFacetValue_21;
    private static java.lang.reflect.Method $method_getClsesWithMatchingDirectTemplateSlotValue_22;
    private static java.lang.reflect.Method $method_getDirectDomain_23;
    private static java.lang.reflect.Method $method_getDirectInstances_24;
    private static java.lang.reflect.Method $method_getDirectOwnSlotValues_25;
    private static java.lang.reflect.Method $method_getDirectOwnSlotValuesClosure_26;
    private static java.lang.reflect.Method $method_getDirectOwnSlotValuesCount_27;
    private static java.lang.reflect.Method $method_getDirectSubclasses_28;
    private static java.lang.reflect.Method $method_getDirectSubslots_29;
    private static java.lang.reflect.Method $method_getDirectSuperclasses_30;
    private static java.lang.reflect.Method $method_getDirectSuperslots_31;
    private static java.lang.reflect.Method $method_getDirectTemplateFacetValues_32;
    private static java.lang.reflect.Method $method_getDirectTemplateSlotValues_33;
    private static java.lang.reflect.Method $method_getDirectTemplateSlots_34;
    private static java.lang.reflect.Method $method_getDirectTypes_35;
    private static java.lang.reflect.Method $method_getDirectlyOverriddenTemplateFacets_36;
    private static java.lang.reflect.Method $method_getDirectlyOverriddenTemplateSlots_37;
    private static java.lang.reflect.Method $method_getDomain_38;
    private static java.lang.reflect.Method $method_getEvents_39;
    private static java.lang.reflect.Method $method_getFacetCount_40;
    private static java.lang.reflect.Method $method_getFacets_41;
    private static java.lang.reflect.Method $method_getFrame_42;
    private static java.lang.reflect.Method $method_getFrame_43;
    private static java.lang.reflect.Method $method_getFrameCount_44;
    private static java.lang.reflect.Method $method_getFrameName_45;
    private static java.lang.reflect.Method $method_getFrameValues_46;
    private static java.lang.reflect.Method $method_getFrames_47;
    private static java.lang.reflect.Method $method_getFramesWithAnyDirectOwnSlotValue_48;
    private static java.lang.reflect.Method $method_getFramesWithDirectOwnSlotValue_49;
    private static java.lang.reflect.Method $method_getFramesWithMatchingDirectOwnSlotValue_50;
    private static java.lang.reflect.Method $method_getInstances_51;
    private static java.lang.reflect.Method $method_getMatchingReferences_52;
    private static java.lang.reflect.Method $method_getOverriddenTemplateFacets_53;
    private static java.lang.reflect.Method $method_getOverriddenTemplateSlots_54;
    private static java.lang.reflect.Method $method_getOwnFacetValues_55;
    private static java.lang.reflect.Method $method_getOwnFacets_56;
    private static java.lang.reflect.Method $method_getOwnSlotValues_57;
    private static java.lang.reflect.Method $method_getOwnSlots_58;
    private static java.lang.reflect.Method $method_getReferences_59;
    private static java.lang.reflect.Method $method_getSimpleInstanceCount_60;
    private static java.lang.reflect.Method $method_getSlotCount_61;
    private static java.lang.reflect.Method $method_getSlots_62;
    private static java.lang.reflect.Method $method_getSubclasses_63;
    private static java.lang.reflect.Method $method_getSubslots_64;
    private static java.lang.reflect.Method $method_getSuperclasses_65;
    private static java.lang.reflect.Method $method_getSuperslots_66;
    private static java.lang.reflect.Method $method_getTemplateFacetValues_67;
    private static java.lang.reflect.Method $method_getTemplateFacets_68;
    private static java.lang.reflect.Method $method_getTemplateSlotValues_69;
    private static java.lang.reflect.Method $method_getTemplateSlots_70;
    private static java.lang.reflect.Method $method_getTypes_71;
    private static java.lang.reflect.Method $method_moveDirectSubclass_72;
    private static java.lang.reflect.Method $method_moveDirectSubslot_73;
    private static java.lang.reflect.Method $method_moveDirectTemplateSlot_74;
    private static java.lang.reflect.Method $method_preload_75;
    private static java.lang.reflect.Method $method_removeDirectSuperclass_76;
    private static java.lang.reflect.Method $method_removeDirectSuperslot_77;
    private static java.lang.reflect.Method $method_removeDirectTemplateFacetOverrides_78;
    private static java.lang.reflect.Method $method_removeDirectTemplateSlot_79;
    private static java.lang.reflect.Method $method_removeDirectType_80;
    private static java.lang.reflect.Method $method_rollbackTransaction_81;
    private static java.lang.reflect.Method $method_setDirectOwnSlotValues_82;
    private static java.lang.reflect.Method $method_setDirectTemplateFacetValues_83;
    private static java.lang.reflect.Method $method_setDirectTemplateSlotValues_84;
    private static java.lang.reflect.Method $method_setFrameName_85;
    
    static {
	try {
	    $method_addDirectSuperclass_0 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("addDirectSuperclass", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_addDirectSuperslot_1 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("addDirectSuperslot", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_addDirectTemplateSlot_2 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("addDirectTemplateSlot", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_addDirectType_3 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("addDirectType", new java.lang.Class[] {edu.stanford.smi.protege.model.Instance.class, edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_beginTransaction_4 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("beginTransaction", new java.lang.Class[] {java.lang.String.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_close_5 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("close", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_commitTransaction_6 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("commitTransaction", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_createCls_7 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("createCls", new java.lang.Class[] {edu.stanford.smi.protege.model.FrameID.class, java.lang.String.class, java.util.Collection.class, java.util.Collection.class, boolean.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_createFacet_8 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("createFacet", new java.lang.Class[] {edu.stanford.smi.protege.model.FrameID.class, java.lang.String.class, java.util.Collection.class, boolean.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_createSimpleInstance_9 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("createSimpleInstance", new java.lang.Class[] {edu.stanford.smi.protege.model.FrameID.class, java.lang.String.class, java.util.Collection.class, boolean.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_createSlot_10 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("createSlot", new java.lang.Class[] {edu.stanford.smi.protege.model.FrameID.class, java.lang.String.class, java.util.Collection.class, java.util.Collection.class, boolean.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_deleteCls_11 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("deleteCls", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_deleteFacet_12 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("deleteFacet", new java.lang.Class[] {edu.stanford.smi.protege.model.Facet.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_deleteSimpleInstance_13 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("deleteSimpleInstance", new java.lang.Class[] {edu.stanford.smi.protege.model.SimpleInstance.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_deleteSlot_14 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("deleteSlot", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_executeQuery_15 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("executeQuery", new java.lang.Class[] {edu.stanford.smi.protege.model.query.Query.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsCount_16 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsCount", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClses_17 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClses", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsesWithAnyDirectTemplateSlotValue_18 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsesWithAnyDirectTemplateSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsesWithDirectTemplateFacetValue_19 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsesWithDirectTemplateFacetValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, java.lang.Object.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsesWithDirectTemplateSlotValue_20 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsesWithDirectTemplateSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, java.lang.Object.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsesWithMatchingDirectTemplateFacetValue_21 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsesWithMatchingDirectTemplateFacetValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, java.lang.String.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getClsesWithMatchingDirectTemplateSlotValue_22 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getClsesWithMatchingDirectTemplateSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, java.lang.String.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectDomain_23 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectDomain", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectInstances_24 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectInstances", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectOwnSlotValues_25 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectOwnSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectOwnSlotValuesClosure_26 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectOwnSlotValuesClosure", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectOwnSlotValuesCount_27 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectOwnSlotValuesCount", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectSubclasses_28 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectSubclasses", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectSubslots_29 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectSubslots", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectSuperclasses_30 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectSuperclasses", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectSuperslots_31 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectSuperslots", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectTemplateFacetValues_32 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectTemplateFacetValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectTemplateSlotValues_33 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectTemplateSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectTemplateSlots_34 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectTemplateSlots", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectTypes_35 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectTypes", new java.lang.Class[] {edu.stanford.smi.protege.model.Instance.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectlyOverriddenTemplateFacets_36 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectlyOverriddenTemplateFacets", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDirectlyOverriddenTemplateSlots_37 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDirectlyOverriddenTemplateSlots", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getDomain_38 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getDomain", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getEvents_39 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getEvents", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFacetCount_40 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFacetCount", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFacets_41 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFacets", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrame_42 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrame", new java.lang.Class[] {edu.stanford.smi.protege.model.FrameID.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrame_43 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrame", new java.lang.Class[] {java.lang.String.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrameCount_44 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrameCount", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrameName_45 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrameName", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrameValues_46 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrameValues", new java.lang.Class[] {java.util.Collection.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFrames_47 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFrames", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFramesWithAnyDirectOwnSlotValue_48 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFramesWithAnyDirectOwnSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFramesWithDirectOwnSlotValue_49 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFramesWithDirectOwnSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, java.lang.Object.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getFramesWithMatchingDirectOwnSlotValue_50 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getFramesWithMatchingDirectOwnSlotValue", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, java.lang.String.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getInstances_51 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getInstances", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getMatchingReferences_52 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getMatchingReferences", new java.lang.Class[] {java.lang.String.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOverriddenTemplateFacets_53 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOverriddenTemplateFacets", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOverriddenTemplateSlots_54 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOverriddenTemplateSlots", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOwnFacetValues_55 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOwnFacetValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOwnFacets_56 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOwnFacets", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOwnSlotValues_57 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOwnSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getOwnSlots_58 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getOwnSlots", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getReferences_59 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getReferences", new java.lang.Class[] {java.lang.Object.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSimpleInstanceCount_60 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSimpleInstanceCount", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSlotCount_61 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSlotCount", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSlots_62 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSlots", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSubclasses_63 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSubclasses", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSubslots_64 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSubslots", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSuperclasses_65 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSuperclasses", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getSuperslots_66 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getSuperslots", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getTemplateFacetValues_67 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getTemplateFacetValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getTemplateFacets_68 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getTemplateFacets", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getTemplateSlotValues_69 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getTemplateSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getTemplateSlots_70 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getTemplateSlots", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_getTypes_71 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("getTypes", new java.lang.Class[] {edu.stanford.smi.protege.model.Instance.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_moveDirectSubclass_72 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("moveDirectSubclass", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Cls.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_moveDirectSubslot_73 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("moveDirectSubslot", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Slot.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_moveDirectTemplateSlot_74 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("moveDirectTemplateSlot", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, int.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_preload_75 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("preload", new java.lang.Class[] {boolean.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_removeDirectSuperclass_76 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("removeDirectSuperclass", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_removeDirectSuperslot_77 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("removeDirectSuperslot", new java.lang.Class[] {edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_removeDirectTemplateFacetOverrides_78 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("removeDirectTemplateFacetOverrides", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_removeDirectTemplateSlot_79 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("removeDirectTemplateSlot", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_removeDirectType_80 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("removeDirectType", new java.lang.Class[] {edu.stanford.smi.protege.model.Instance.class, edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_rollbackTransaction_81 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("rollbackTransaction", new java.lang.Class[] {edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_setDirectOwnSlotValues_82 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("setDirectOwnSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, edu.stanford.smi.protege.model.Slot.class, java.util.Collection.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_setDirectTemplateFacetValues_83 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("setDirectTemplateFacetValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, edu.stanford.smi.protege.model.Facet.class, java.util.Collection.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_setDirectTemplateSlotValues_84 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("setDirectTemplateSlotValues", new java.lang.Class[] {edu.stanford.smi.protege.model.Cls.class, edu.stanford.smi.protege.model.Slot.class, java.util.Collection.class, edu.stanford.smi.protege.server.RemoteSession.class});
	    $method_setFrameName_85 = edu.stanford.smi.protege.server.RemoteServerFrameStore.class.getMethod("setFrameName", new java.lang.Class[] {edu.stanford.smi.protege.model.Frame.class, java.lang.String.class, edu.stanford.smi.protege.server.RemoteSession.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ServerFrameStore_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addDirectSuperclass(Cls, Cls, RemoteSession)
    public void addDirectSuperclass(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Cls $param_Cls_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addDirectSuperclass_0, new java.lang.Object[] {$param_Cls_1, $param_Cls_2, $param_RemoteSession_3}, -5610860536594020007L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addDirectSuperslot(Slot, Slot, RemoteSession)
    public void addDirectSuperslot(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addDirectSuperslot_1, new java.lang.Object[] {$param_Slot_1, $param_Slot_2, $param_RemoteSession_3}, 7116812953401642530L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addDirectTemplateSlot(Cls, Slot, RemoteSession)
    public void addDirectTemplateSlot(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addDirectTemplateSlot_2, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -5035642370448955844L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of addDirectType(Instance, Cls, RemoteSession)
    public void addDirectType(edu.stanford.smi.protege.model.Instance $param_Instance_1, edu.stanford.smi.protege.model.Cls $param_Cls_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addDirectType_3, new java.lang.Object[] {$param_Instance_1, $param_Cls_2, $param_RemoteSession_3}, 1902213992648421408L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of beginTransaction(String, RemoteSession)
    public boolean beginTransaction(java.lang.String $param_String_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_beginTransaction_4, new java.lang.Object[] {$param_String_1, $param_RemoteSession_2}, 2402857999604086129L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of close(RemoteSession)
    public void close(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_close_5, new java.lang.Object[] {$param_RemoteSession_1}, 5302689019006439689L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of commitTransaction(RemoteSession)
    public boolean commitTransaction(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_commitTransaction_6, new java.lang.Object[] {$param_RemoteSession_1}, 7707416611781411713L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createCls(FrameID, String, Collection, Collection, boolean, RemoteSession)
    public edu.stanford.smi.protege.model.Cls createCls(edu.stanford.smi.protege.model.FrameID $param_FrameID_1, java.lang.String $param_String_2, java.util.Collection $param_Collection_3, java.util.Collection $param_Collection_4, boolean $param_boolean_5, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_6)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createCls_7, new java.lang.Object[] {$param_FrameID_1, $param_String_2, $param_Collection_3, $param_Collection_4, new java.lang.Boolean($param_boolean_5), $param_RemoteSession_6}, -1568208594236619052L);
	    return ((edu.stanford.smi.protege.model.Cls) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createFacet(FrameID, String, Collection, boolean, RemoteSession)
    public edu.stanford.smi.protege.model.Facet createFacet(edu.stanford.smi.protege.model.FrameID $param_FrameID_1, java.lang.String $param_String_2, java.util.Collection $param_Collection_3, boolean $param_boolean_4, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_5)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createFacet_8, new java.lang.Object[] {$param_FrameID_1, $param_String_2, $param_Collection_3, new java.lang.Boolean($param_boolean_4), $param_RemoteSession_5}, 3961804506814360534L);
	    return ((edu.stanford.smi.protege.model.Facet) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createSimpleInstance(FrameID, String, Collection, boolean, RemoteSession)
    public edu.stanford.smi.protege.model.SimpleInstance createSimpleInstance(edu.stanford.smi.protege.model.FrameID $param_FrameID_1, java.lang.String $param_String_2, java.util.Collection $param_Collection_3, boolean $param_boolean_4, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_5)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createSimpleInstance_9, new java.lang.Object[] {$param_FrameID_1, $param_String_2, $param_Collection_3, new java.lang.Boolean($param_boolean_4), $param_RemoteSession_5}, 965080023190560077L);
	    return ((edu.stanford.smi.protege.model.SimpleInstance) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createSlot(FrameID, String, Collection, Collection, boolean, RemoteSession)
    public edu.stanford.smi.protege.model.Slot createSlot(edu.stanford.smi.protege.model.FrameID $param_FrameID_1, java.lang.String $param_String_2, java.util.Collection $param_Collection_3, java.util.Collection $param_Collection_4, boolean $param_boolean_5, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_6)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createSlot_10, new java.lang.Object[] {$param_FrameID_1, $param_String_2, $param_Collection_3, $param_Collection_4, new java.lang.Boolean($param_boolean_5), $param_RemoteSession_6}, -2570575563228882779L);
	    return ((edu.stanford.smi.protege.model.Slot) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteCls(Cls, RemoteSession)
    public void deleteCls(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteCls_11, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -141503492956003897L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteFacet(Facet, RemoteSession)
    public void deleteFacet(edu.stanford.smi.protege.model.Facet $param_Facet_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteFacet_12, new java.lang.Object[] {$param_Facet_1, $param_RemoteSession_2}, -4107984925996412495L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteSimpleInstance(SimpleInstance, RemoteSession)
    public void deleteSimpleInstance(edu.stanford.smi.protege.model.SimpleInstance $param_SimpleInstance_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteSimpleInstance_13, new java.lang.Object[] {$param_SimpleInstance_1, $param_RemoteSession_2}, -599877166275032591L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteSlot(Slot, RemoteSession)
    public void deleteSlot(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteSlot_14, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -8539291000152233330L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of executeQuery(Query, RemoteSession)
    public java.util.Set executeQuery(edu.stanford.smi.protege.model.query.Query $param_Query_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_executeQuery_15, new java.lang.Object[] {$param_Query_1, $param_RemoteSession_2}, 2523070305531131656L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsCount(RemoteSession)
    public int getClsCount(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsCount_16, new java.lang.Object[] {$param_RemoteSession_1}, -509882483807496152L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClses(RemoteSession)
    public java.util.Set getClses(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClses_17, new java.lang.Object[] {$param_RemoteSession_1}, -6171090054577856197L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsesWithAnyDirectTemplateSlotValue(Slot, RemoteSession)
    public java.util.Set getClsesWithAnyDirectTemplateSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsesWithAnyDirectTemplateSlotValue_18, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, 8252503391080999928L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsesWithDirectTemplateFacetValue(Slot, Facet, Object, RemoteSession)
    public java.util.Set getClsesWithDirectTemplateFacetValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.model.Facet $param_Facet_2, java.lang.Object $param_Object_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsesWithDirectTemplateFacetValue_19, new java.lang.Object[] {$param_Slot_1, $param_Facet_2, $param_Object_3, $param_RemoteSession_4}, 3100842852757068822L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsesWithDirectTemplateSlotValue(Slot, Object, RemoteSession)
    public java.util.Set getClsesWithDirectTemplateSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, java.lang.Object $param_Object_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsesWithDirectTemplateSlotValue_20, new java.lang.Object[] {$param_Slot_1, $param_Object_2, $param_RemoteSession_3}, -5884065235219808567L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsesWithMatchingDirectTemplateFacetValue(Slot, Facet, String, int, RemoteSession)
    public java.util.Set getClsesWithMatchingDirectTemplateFacetValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.model.Facet $param_Facet_2, java.lang.String $param_String_3, int $param_int_4, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_5)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsesWithMatchingDirectTemplateFacetValue_21, new java.lang.Object[] {$param_Slot_1, $param_Facet_2, $param_String_3, new java.lang.Integer($param_int_4), $param_RemoteSession_5}, -7772631619928539816L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getClsesWithMatchingDirectTemplateSlotValue(Slot, String, int, RemoteSession)
    public java.util.Set getClsesWithMatchingDirectTemplateSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, java.lang.String $param_String_2, int $param_int_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getClsesWithMatchingDirectTemplateSlotValue_22, new java.lang.Object[] {$param_Slot_1, $param_String_2, new java.lang.Integer($param_int_3), $param_RemoteSession_4}, -9198342235518800064L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectDomain(Slot, RemoteSession)
    public java.util.List getDirectDomain(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectDomain_23, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, 6181783431958123255L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectInstances(Cls, RemoteSession)
    public java.util.List getDirectInstances(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectInstances_24, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, 5658479085014566179L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectOwnSlotValues(Frame, Slot, RemoteSession)
    public java.util.List getDirectOwnSlotValues(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectOwnSlotValues_25, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_RemoteSession_3}, -3223807448668152097L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectOwnSlotValuesClosure(Frame, Slot, RemoteSession)
    public java.util.Set getDirectOwnSlotValuesClosure(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectOwnSlotValuesClosure_26, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_RemoteSession_3}, -7623172840573910687L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectOwnSlotValuesCount(Frame, Slot, RemoteSession)
    public int getDirectOwnSlotValuesCount(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectOwnSlotValuesCount_27, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_RemoteSession_3}, -7307264131122339811L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectSubclasses(Cls, RemoteSession)
    public java.util.List getDirectSubclasses(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectSubclasses_28, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -6505153451971006468L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectSubslots(Slot, RemoteSession)
    public java.util.List getDirectSubslots(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectSubslots_29, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -12919421225514527L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectSuperclasses(Cls, RemoteSession)
    public java.util.List getDirectSuperclasses(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectSuperclasses_30, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -695061993573897383L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectSuperslots(Slot, RemoteSession)
    public java.util.List getDirectSuperslots(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectSuperslots_31, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -5439283480799426616L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectTemplateFacetValues(Cls, Slot, Facet, RemoteSession)
    public java.util.List getDirectTemplateFacetValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.model.Facet $param_Facet_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectTemplateFacetValues_32, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_Facet_3, $param_RemoteSession_4}, -636415946955580386L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectTemplateSlotValues(Cls, Slot, RemoteSession)
    public java.util.List getDirectTemplateSlotValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectTemplateSlotValues_33, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -5247423796542903525L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectTemplateSlots(Cls, RemoteSession)
    public java.util.List getDirectTemplateSlots(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectTemplateSlots_34, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -1325717992697662262L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectTypes(Instance, RemoteSession)
    public java.util.List getDirectTypes(edu.stanford.smi.protege.model.Instance $param_Instance_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectTypes_35, new java.lang.Object[] {$param_Instance_1, $param_RemoteSession_2}, 2244480489060051006L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectlyOverriddenTemplateFacets(Cls, Slot, RemoteSession)
    public java.util.Set getDirectlyOverriddenTemplateFacets(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectlyOverriddenTemplateFacets_36, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, 4591002843020536828L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDirectlyOverriddenTemplateSlots(Cls, RemoteSession)
    public java.util.Set getDirectlyOverriddenTemplateSlots(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDirectlyOverriddenTemplateSlots_37, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, 7786346196624302483L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDomain(Slot, RemoteSession)
    public java.util.Set getDomain(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDomain_38, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -1799384780364662694L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getEvents(RemoteSession)
    public java.util.List getEvents(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getEvents_39, new java.lang.Object[] {$param_RemoteSession_1}, 1464572772953868073L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFacetCount(RemoteSession)
    public int getFacetCount(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFacetCount_40, new java.lang.Object[] {$param_RemoteSession_1}, -3756444135134594700L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFacets(RemoteSession)
    public java.util.Set getFacets(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFacets_41, new java.lang.Object[] {$param_RemoteSession_1}, 5287477769628610471L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrame(FrameID, RemoteSession)
    public edu.stanford.smi.protege.model.Frame getFrame(edu.stanford.smi.protege.model.FrameID $param_FrameID_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrame_42, new java.lang.Object[] {$param_FrameID_1, $param_RemoteSession_2}, -5580899682868097341L);
	    return ((edu.stanford.smi.protege.model.Frame) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrame(String, RemoteSession)
    public edu.stanford.smi.protege.model.Frame getFrame(java.lang.String $param_String_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrame_43, new java.lang.Object[] {$param_String_1, $param_RemoteSession_2}, 3191725554915436376L);
	    return ((edu.stanford.smi.protege.model.Frame) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrameCount(RemoteSession)
    public int getFrameCount(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrameCount_44, new java.lang.Object[] {$param_RemoteSession_1}, 4409426202913781279L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrameName(Frame, RemoteSession)
    public java.lang.String getFrameName(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrameName_45, new java.lang.Object[] {$param_Frame_1, $param_RemoteSession_2}, -7963024535861349604L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrameValues(Collection, RemoteSession)
    public java.util.Map getFrameValues(java.util.Collection $param_Collection_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrameValues_46, new java.lang.Object[] {$param_Collection_1, $param_RemoteSession_2}, -7537576579396866498L);
	    return ((java.util.Map) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFrames(RemoteSession)
    public java.util.Set getFrames(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFrames_47, new java.lang.Object[] {$param_RemoteSession_1}, 8605128879610636719L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFramesWithAnyDirectOwnSlotValue(Slot, RemoteSession)
    public java.util.Set getFramesWithAnyDirectOwnSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFramesWithAnyDirectOwnSlotValue_48, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -627140467059292064L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFramesWithDirectOwnSlotValue(Slot, Object, RemoteSession)
    public java.util.Set getFramesWithDirectOwnSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, java.lang.Object $param_Object_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFramesWithDirectOwnSlotValue_49, new java.lang.Object[] {$param_Slot_1, $param_Object_2, $param_RemoteSession_3}, -8504298020624761617L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getFramesWithMatchingDirectOwnSlotValue(Slot, String, int, RemoteSession)
    public java.util.Set getFramesWithMatchingDirectOwnSlotValue(edu.stanford.smi.protege.model.Slot $param_Slot_1, java.lang.String $param_String_2, int $param_int_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getFramesWithMatchingDirectOwnSlotValue_50, new java.lang.Object[] {$param_Slot_1, $param_String_2, new java.lang.Integer($param_int_3), $param_RemoteSession_4}, 4817812254701428663L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getInstances(Cls, RemoteSession)
    public java.util.Set getInstances(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getInstances_51, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -6559514331202863734L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getMatchingReferences(String, int, RemoteSession)
    public java.util.Set getMatchingReferences(java.lang.String $param_String_1, int $param_int_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMatchingReferences_52, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2), $param_RemoteSession_3}, 2417343572843862544L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOverriddenTemplateFacets(Cls, Slot, RemoteSession)
    public java.util.Set getOverriddenTemplateFacets(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOverriddenTemplateFacets_53, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -7884548010720278419L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOverriddenTemplateSlots(Cls, RemoteSession)
    public java.util.Set getOverriddenTemplateSlots(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOverriddenTemplateSlots_54, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -3037521981261557812L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOwnFacetValues(Frame, Slot, Facet, RemoteSession)
    public java.util.Collection getOwnFacetValues(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.model.Facet $param_Facet_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOwnFacetValues_55, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_Facet_3, $param_RemoteSession_4}, 8862161658039328980L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOwnFacets(Frame, Slot, RemoteSession)
    public java.util.Set getOwnFacets(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOwnFacets_56, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_RemoteSession_3}, 7497838670956837807L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOwnSlotValues(Frame, Slot, RemoteSession)
    public java.util.Collection getOwnSlotValues(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOwnSlotValues_57, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_RemoteSession_3}, -6204811068385039035L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOwnSlots(Frame, RemoteSession)
    public java.util.Set getOwnSlots(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOwnSlots_58, new java.lang.Object[] {$param_Frame_1, $param_RemoteSession_2}, 461442578610608924L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getReferences(Object, RemoteSession)
    public java.util.Set getReferences(java.lang.Object $param_Object_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getReferences_59, new java.lang.Object[] {$param_Object_1, $param_RemoteSession_2}, -3723473120285379343L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSimpleInstanceCount(RemoteSession)
    public int getSimpleInstanceCount(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSimpleInstanceCount_60, new java.lang.Object[] {$param_RemoteSession_1}, 4202072932918181897L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSlotCount(RemoteSession)
    public int getSlotCount(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSlotCount_61, new java.lang.Object[] {$param_RemoteSession_1}, -4403937944591267070L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSlots(RemoteSession)
    public java.util.Set getSlots(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSlots_62, new java.lang.Object[] {$param_RemoteSession_1}, 3578182661453316277L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSubclasses(Cls, RemoteSession)
    public java.util.Set getSubclasses(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSubclasses_63, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -8195302885781192628L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSubslots(Slot, RemoteSession)
    public java.util.Set getSubslots(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSubslots_64, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, -2656801373492680055L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSuperclasses(Cls, RemoteSession)
    public java.util.Set getSuperclasses(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSuperclasses_65, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, -3854643750156841655L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getSuperslots(Slot, RemoteSession)
    public java.util.Set getSuperslots(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getSuperslots_66, new java.lang.Object[] {$param_Slot_1, $param_RemoteSession_2}, 9167731242645193943L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTemplateFacetValues(Cls, Slot, Facet, RemoteSession)
    public java.util.Collection getTemplateFacetValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.model.Facet $param_Facet_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTemplateFacetValues_67, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_Facet_3, $param_RemoteSession_4}, 302894371510626777L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTemplateFacets(Cls, Slot, RemoteSession)
    public java.util.Set getTemplateFacets(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTemplateFacets_68, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -6272831493451040643L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTemplateSlotValues(Cls, Slot, RemoteSession)
    public java.util.Collection getTemplateSlotValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTemplateSlotValues_69, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -5059506870148745845L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTemplateSlots(Cls, RemoteSession)
    public java.util.Set getTemplateSlots(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTemplateSlots_70, new java.lang.Object[] {$param_Cls_1, $param_RemoteSession_2}, 885042636123344977L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTypes(Instance, RemoteSession)
    public java.util.Set getTypes(edu.stanford.smi.protege.model.Instance $param_Instance_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTypes_71, new java.lang.Object[] {$param_Instance_1, $param_RemoteSession_2}, -2065075309657197029L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of moveDirectSubclass(Cls, Cls, int, RemoteSession)
    public void moveDirectSubclass(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Cls $param_Cls_2, int $param_int_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_moveDirectSubclass_72, new java.lang.Object[] {$param_Cls_1, $param_Cls_2, new java.lang.Integer($param_int_3), $param_RemoteSession_4}, -4763681098257844589L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of moveDirectSubslot(Slot, Slot, int, RemoteSession)
    public void moveDirectSubslot(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, int $param_int_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_moveDirectSubslot_73, new java.lang.Object[] {$param_Slot_1, $param_Slot_2, new java.lang.Integer($param_int_3), $param_RemoteSession_4}, -8471725442696800293L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of moveDirectTemplateSlot(Cls, Slot, int, RemoteSession)
    public void moveDirectTemplateSlot(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, int $param_int_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_moveDirectTemplateSlot_74, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, new java.lang.Integer($param_int_3), $param_RemoteSession_4}, 384443750941345717L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of preload(boolean, RemoteSession)
    public java.util.Map preload(boolean $param_boolean_1, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_preload_75, new java.lang.Object[] {new java.lang.Boolean($param_boolean_1), $param_RemoteSession_2}, 3297179398376787612L);
	    return ((java.util.Map) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeDirectSuperclass(Cls, Cls, RemoteSession)
    public void removeDirectSuperclass(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Cls $param_Cls_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeDirectSuperclass_76, new java.lang.Object[] {$param_Cls_1, $param_Cls_2, $param_RemoteSession_3}, 9137215973576905607L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeDirectSuperslot(Slot, Slot, RemoteSession)
    public void removeDirectSuperslot(edu.stanford.smi.protege.model.Slot $param_Slot_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeDirectSuperslot_77, new java.lang.Object[] {$param_Slot_1, $param_Slot_2, $param_RemoteSession_3}, 1807858827345604103L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeDirectTemplateFacetOverrides(Cls, Slot, RemoteSession)
    public void removeDirectTemplateFacetOverrides(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeDirectTemplateFacetOverrides_78, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, -7893540488951765415L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeDirectTemplateSlot(Cls, Slot, RemoteSession)
    public void removeDirectTemplateSlot(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeDirectTemplateSlot_79, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_RemoteSession_3}, 4459114215641827748L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeDirectType(Instance, Cls, RemoteSession)
    public void removeDirectType(edu.stanford.smi.protege.model.Instance $param_Instance_1, edu.stanford.smi.protege.model.Cls $param_Cls_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeDirectType_80, new java.lang.Object[] {$param_Instance_1, $param_Cls_2, $param_RemoteSession_3}, -5469535989969118508L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of rollbackTransaction(RemoteSession)
    public boolean rollbackTransaction(edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_rollbackTransaction_81, new java.lang.Object[] {$param_RemoteSession_1}, 3009422084734366699L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setDirectOwnSlotValues(Frame, Slot, Collection, RemoteSession)
    public void setDirectOwnSlotValues(edu.stanford.smi.protege.model.Frame $param_Frame_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, java.util.Collection $param_Collection_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setDirectOwnSlotValues_82, new java.lang.Object[] {$param_Frame_1, $param_Slot_2, $param_Collection_3, $param_RemoteSession_4}, -809892014556077100L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setDirectTemplateFacetValues(Cls, Slot, Facet, Collection, RemoteSession)
    public void setDirectTemplateFacetValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, edu.stanford.smi.protege.model.Facet $param_Facet_3, java.util.Collection $param_Collection_4, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_5)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setDirectTemplateFacetValues_83, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_Facet_3, $param_Collection_4, $param_RemoteSession_5}, -2818077657293479910L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setDirectTemplateSlotValues(Cls, Slot, Collection, RemoteSession)
    public void setDirectTemplateSlotValues(edu.stanford.smi.protege.model.Cls $param_Cls_1, edu.stanford.smi.protege.model.Slot $param_Slot_2, java.util.Collection $param_Collection_3, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setDirectTemplateSlotValues_84, new java.lang.Object[] {$param_Cls_1, $param_Slot_2, $param_Collection_3, $param_RemoteSession_4}, 290129328092861470L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setFrameName(Frame, String, RemoteSession)
    public void setFrameName(edu.stanford.smi.protege.model.Frame $param_Frame_1, java.lang.String $param_String_2, edu.stanford.smi.protege.server.RemoteSession $param_RemoteSession_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setFrameName_85, new java.lang.Object[] {$param_Frame_1, $param_String_2, $param_RemoteSession_3}, 7882771145715336691L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
